stages:
  stage1:
    - step1
  stage2:
    - step1

steps:
  step1:
    image: golang 
    command: |
      echo "hello world"
      go install golang.org/x/lint/golint@latest
      golint ./...
    
